from pathlib import Path
import unittest


class WorkerContractTest(unittest.TestCase):
    def test_worker_returns_all_positions_and_active_position(self):
        source = Path("workers/okx-account-worker.js").read_text(encoding="utf-8")
        self.assertIn("function parsePositions", source)
        self.assertIn("function selectActivePosition", source)
        self.assertIn("positions: parsedPositions", source)
        self.assertIn("hasHedgedPositions: parsedPositions.length > 1", source)
        self.assertIn("Cache-Control", source)
        self.assertIn("no-store", source)
        self.assertIn("function weeklyPerformance", source)
        self.assertIn("weekProfitCny", source)
        self.assertIn("weeklyLossLimitCny", source)
        self.assertIn("weeklyRiskStatus", source)
        self.assertIn("function macroBrief", source)
        self.assertIn('url.pathname === "/macro"', source)
        self.assertIn("UPCOMING_MACRO_WINDOW_MS", source)
        self.assertIn("upcomingWindowHours", source)
        self.assertIn("未来7天暂无已接入的高影响宏观事件", source)
        self.assertIn("美联储9月15-16日FOMC议息观察窗口", source)
        self.assertIn("placeholder: true", source)
        self.assertIn("function officialMacroEvents", source)
        self.assertIn("recentReleasedEvents", source)
        self.assertIn("upcomingEvents", source)
        self.assertIn("RECENT_MACRO_KEEP_MS", source)
        self.assertIn("美国7月CPI通胀数据", source)
        self.assertIn("macroStatus", source)
        self.assertIn("function policyCryptoEvents", source)
        self.assertIn("policyCryptoEvents", source)
        self.assertIn("白宫加密会议推动CLARITY Act", source)
        self.assertIn("Strategic Bitcoin Reserve", source)
        self.assertIn("加密政策", source)
        self.assertIn("SIM_ACCOUNT_STATE_V1", source)
        self.assertIn("SIM_INITIAL_CNY", source)
        self.assertIn("function simBrief", source)
        self.assertIn('url.pathname === "/sim"', source)
        self.assertIn('url.pathname === "/sim/reset"', source)
        self.assertIn("runSimDecision", source)
        self.assertIn("SIM_MAX_LOSS_PCT", source)
        self.assertIn("SIM_TARGET_CNY", source)
        self.assertIn("SIM_SPRINT_DAYS", source)
        self.assertIn("SIM_BLOWUP_RESTART_CNY", source)
        self.assertIn("SIM_BASE_LEVERAGE", source)
        self.assertIn("SIM_STRONG_LEVERAGE", source)
        self.assertIn("SIM_MAX_LEVERAGE", source)
        self.assertIn("function simSignalProfile", source)
        self.assertIn("SIM_MIN_EXPECTED_RR", source)
        self.assertIn("function classifyMarketRegime", source)
        self.assertIn("function detectBestSetup", source)
        self.assertIn("function simRiskCheck", source)
        self.assertIn("expectedRR", source)
        self.assertIn("marketRegime", source)
        self.assertIn("selectedSetup", source)
        self.assertIn("结构止损", source)
        self.assertIn("冲刺动量多", source)
        self.assertIn("冲刺动量空", source)
        self.assertIn("亏完重开模拟", source)
        self.assertIn("aggressive_sprint", source)
        self.assertIn("interval=1m", source)
        self.assertIn("binanceSimMarketSnapshot", source)
        self.assertIn("Binance USD-M备用行情", source)
        self.assertIn("bybitSimMarketSnapshot", source)
        self.assertIn("Bybit线性合约备用行情", source)


if __name__ == "__main__":
    unittest.main()
