from pathlib import Path
import unittest


class RenderLivePlanTest(unittest.TestCase):
    def test_live_plan_recalculates_by_position_side(self):
        source = Path("btc_report/render.py").read_text(encoding="utf-8")
        self.assertIn("function buildShortPlan", source)
        self.assertIn("function buildLongPlan", source)
        self.assertIn("function buildFlatPlan", source)
        self.assertIn("function currentPositionPlanKey", source)
        self.assertIn("function getOrBuildLockedPositionPlan", source)
        self.assertIn("function triggerStatusText", source)
        self.assertIn("lockedPositionPlanKey === key", source)
        self.assertIn("simpleTriggerStatus", source)
        self.assertIn("updateSimplePlan(liveLatest, liveSupport, liveResistance, 'OKX账户实时同步')", source)
        self.assertIn("positionConfig.activeSide = 'flat'", source)
        self.assertIn("side === 'short'", source)
        self.assertIn("side === 'long'", source)
        self.assertIn("实时账户接口未配置，持仓不会同步", source)
        self.assertIn("account-15s-sync", source)
        self.assertIn("refreshAccountSoon('websocket-price-sync')", source)
        self.assertIn("function v5SameLifecycle", source)
        self.assertIn("BTC_LOCKED_POSITION_PLAN_V5", source)
        self.assertIn("Math.abs(entry / Number(plan.entry || 0) - 1) > 0.0015", source)
        self.assertIn("Math.abs(qty / Number(plan.qty || 0) - 1) > 0.10", source)
        self.assertIn("重新锁定计划", source)
        self.assertIn("REST-15s-score-sync", source)
        self.assertIn("function v5Score", source)
        self.assertIn("strategyLongScore", source)
        self.assertIn("refreshMacroEvents", source)
        self.assertIn("macroEventsList", source)
        self.assertIn("recentMacroEventsList", source)
        self.assertIn("macroWarnings", source)
        self.assertIn("最近7天关键消息", source)
        self.assertIn("function sprintStageForCny", source)
        self.assertIn("applySprintStageFromEquity", source)
        self.assertIn("sprintStageName", source)
        self.assertIn("阶段2：10000 -> 30000元", source)
        self.assertIn("OKX接口权益", source)
        self.assertIn("earlyLongWarning", source)
        self.assertIn("earlyShortWarning", source)
        self.assertIn("function v5BuildEarlyMetrics", source)
        self.assertIn("function v5EarlyWarningScore", source)
        self.assertIn("function updateEarlyWarningUi", source)
        self.assertIn("candle1m", source)
        self.assertIn("candle5m", source)
        self.assertIn("提前做多观察位", source)
        self.assertIn("提前做空观察位", source)
        self.assertIn("预警，不是确认", source)
        self.assertIn("短周期RSI连续回升", source)
        self.assertIn("点位不自动重算", source)


if __name__ == "__main__":
    unittest.main()
